### ISSUE TITLE
Block tweets by pattern matching content

### ISSUE THREAD

**Issue by BruceFletcher** [vhs/vhsbot#8]
Retweets get through the current 'block user' capability. If we could block by content, it would be easier to make effective blocks for popular high school football game tweets and similar.

We'd need to be able to clear the filters easily too, especially since content-based filters could be overly broad.

**Comment by seanhagen** [comment]
I'm currently working on adding some code so that we can block the original tweet, so it'd work like so:
- vhsbot sees a tweet from someuser ( TWEET1 )
- vhsbot sees a retweet of TWEET1 ( RT1 )
  - vhsbot stores the id of the original tweet ( something that comes from the json of RT1 )
- user tells vhsbot to list last few retweets seen
- vhsbot replies with something like the following

`vhsbot: saw retweet of TWEET1 ( id 1 )`
`vhsbot: saw retweet of TWEET2 ( id 2 )`
- user can then tell vhsbot to ignore retweets of TWEET1: `@vhsbot ignore retweets of 1`
- no more retweets of TWEET1 will be shown

that way, we're not mucking about with regular expressions ( i don't want to have to code a regex tester into vhsbot.... )

**Comment by BruceFletcher** [comment]
That sounds like a better solution to the current problem, but I wouldn't think a regex tester would be that hard to code in. JS provides the regex parser. But if there's metadata to identify a string of tweets, that's definitely the better hook.

**Comment by seanhagen** [comment]
Closing for now, we're now blocking retweets/quotes of blocked users tweets ( god that's a mouthful )(that's what she said).

Unless in the future we really really really really want to add "block via regexp", I think we're good.
